name: CI
on:
  push:
    branches:
      - master
jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    # needs: build-and-test
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: harry408/auth-service-408 # codersgyan/mernstack_auth_service:build-2
      IMAGE_TAG: build-${{ github.run_number }}
    # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --platform linux/amd64 -f docker/prod/Dockerfile .
      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
